# Generated by Django 2.1 on 2018-08-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='selected_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=None, related_name='+', to='report.Report'),
        ),
    ]
