# Generated by Django 2.1 on 2018-09-04 07:39
from django.db import migrations
from django.core.management import call_command


def load_initial_districts(apps, schema_editor):
    call_command('loaddata', 'initial_districts.json', app_label='project')


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180904_0629'),
    ]

    operations = [
        migrations.RunPython(load_initial_districts),
    ]
