# Generated by Django 2.1.2 on 2018-11-15 05:43

from django.db import migrations
from django.core.management import call_command


def load_initial_municipalities(apps, schema_editor):
    call_command('loaddata', 'initial_municipalities.json', app_label='project')


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20181030_0712'),
    ]

    operations = [
        migrations.RunPython(load_initial_municipalities),
    ]
