# Generated by Django 2.1 on 2018-09-13 16:14

from django.db import migrations, models
import report.validators


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_re_extract_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(upload_to='reports/', validators=[report.validators.validate_file_extension]),
        ),
    ]
