# Generated by Django 2.1 on 2018-09-11 08:54

from django.db import migrations
# from django.core.management import call_command


def re_extract_reports(apps, schema_editor):
    # This doesn't work anymore
    # call_command('force_extract_reports')
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('report', '005_re_extract_reports'),
    ]

    operations = [
        migrations.RunPython(re_extract_reports),
    ]
