# Generated by Django 2.1.12 on 2019-09-03 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_reload_municipalities'),
        ('report', '0006_re_extract_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildFamilyParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('child_participation', 'Child Participation'), ('family_participation', 'Family Participation'), ('child_support', 'Child Support'), ('family_support', 'Family Support')], max_length=30)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('participation', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='PresenceAndParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_rc_temporarily_away', models.IntegerField(default=0)),
                ('total_no_of_rc_records_dropped_during_the_month', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectSOI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_closed', models.IntegerField()),
                ('closed_on', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterChildByAgeAndGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('age_range', models.CharField(choices=[('<=6', '<=6'), ('7-12', '7-12'), ('>=13', '>=13')], max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('count', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='registerchildbyageandgender',
            unique_together={('project', 'date', 'age_range', 'gender')},
        ),
        migrations.AlterUniqueTogether(
            name='projectsoi',
            unique_together={('project', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='presenceandparticipation',
            unique_together={('project', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='childfamilyparticipation',
            unique_together={('project', 'date', 'type', 'participation', 'gender')},
        ),
    ]
