# Generated by Django 2.1.12 on 2019-09-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20190903_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsoi',
            name='closed_on',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectsoi',
            name='total_closed',
            field=models.IntegerField(default=0),
        ),
    ]
