# Generated by Django 2.1.12 on 2019-11-07 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20190909_1550'),
        ('report', '0009_report_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagePeopleGroupDisability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('language', models.CharField(max_length=255)),
                ('people_group', models.CharField(max_length=255)),
                ('disability', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.AlterModelOptions(
            name='presenceandparticipation',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='projectsoi',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterUniqueTogether(
            name='languagepeoplegroupdisability',
            unique_together={('project', 'date', 'language', 'people_group', 'disability')},
        ),
    ]
