# Generated by Django 2.1.12 on 2019-12-24 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0010_auto_20191107_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='bulk-import-report/')),
                ('generated_on', models.DateField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10, null=True)),
                ('log_message', models.TextField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-date',), 'verbose_name': 'ADP Management Report', 'verbose_name_plural': 'ADP Management Reports'},
        ),
    ]
