# Generated by Django 2.1.15 on 2020-08-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_project_child_marriage_count'),
        ('report', '0012_auto_20200123_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportPariticipationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='childfamilyparticipation',
            name='type',
            field=models.CharField(choices=[('child_participation', 'Child Participation'), ('family_participation', 'Family Participation'), ('child_support', 'Child Support'), ('family_support', 'Family Support'), ('benefit_support', 'Benefit Support')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='supportpariticipationdetail',
            unique_together={('project', 'date', 'type', 'comment')},
        ),
    ]
