version: "2"
checks:
  complex-logic:
    enabled: true
    config:
        threshold: 10
  file-lines:
    enabled: true
    config:
        threshold: 999
  method-complexity:
    enabled: true
    config:
        threshold: 12
  method-count:
    enabled: true
    config:
        threshold: 20
  method-lines:
    enabled: true
    config:
        threshold: 100
  nested-control-flow:
    enabled: true
    config:
        threshold: 4
  return-statements:
    enabled: true
    config:
        threshold: 5
  argument-count:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false

plugins:
  pycodestyle:
    enabled: true
    checks:
      complexity:
        enabled: false
    config: ./server/tox.ini
  eslint:
    enabled: true
    channel: "eslint-4"
    checks:
      complexity:
        enabled: false
    config:
      config: ./client/.eslintrc
  scss-lint:
    enabled: true
    config: ./client/.scss-lint.yml
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - XXX

exclude_patterns:
- "**/migrations/*"
- "**/tests/*"
- "**/wsgi.py"
- "manage.py"
- "build/"
- "coverage/"
- "config/"
- "scripts/"
- "node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/vendor/"
- "**/*.test.js"
