sudo: required

services:
    - docker

before_install:
    - docker pull devtc/worldvision-dvs:client-latest || true
    - docker pull devtc/worldvision-dvs:server-latest || true

before_script:
    - ./scripts/travis/build.sh

script:
    - echo 'run_test'

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - ./scripts/travis/push.sh
