version: '3.2'

services:
  db:
    image: postgres:9.6
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    image: "docker.pkg.github.com/toggle-corp/worldvision-dvs/server:${WV_BRANCH_NAME:-develop}"
    build:
      context: ./server/
      cache_from:
        - "docker.pkg.github.com/toggle-corp/worldvision-dvs/server:${WV_BRANCH_NAME}"
        - docker.pkg.github.com/toggle-corp/worldvision-dvs/server:develop
    env_file:
      - .env
    command: /code/scripts/run_develop.sh
    volumes:
      - ./server/:/code
      - media:/media
    ports:
      - '8005:8005'
    depends_on:
      - db

  client: &client
    image: "docker.pkg.github.com/toggle-corp/worldvision-dvs/client:${WV_BRANCH_NAME:-develop}"
    build:
      context: ./client/
      cache_from:
        - "docker.pkg.github.com/toggle-corp/worldvision-dvs/client:${WV_BRANCH_NAME}"
        - docker.pkg.github.com/toggle-corp/worldvision-dvs/client:develop
    env_file:
      - .env
    command: bash -c '/code/scripts/run_develop.sh'
    volumes:
      - ./client/:/code
    ports:
      - '3005:3005'

  client-build:
    <<: *client
    command: bash -c 'CI=false yarn build'
    volumes:
      - ./client/build/:/code/build/

volumes:
  media:
  postgres-data:
