version: '3.2'

services:
    db:
        image: postgres:9.6
        volumes:
            - postgres-data:/var/lib/postgresql/data

    server:
        image: docker.pkg.github.com/toggle-corp/worldvision-dvs/server:latest
        build:
          context: ./server/
          cache_from:
            - devtc/worldvision-dvs:server-latest
        env_file:
            - .env
        command: /code/scripts/run_develop.sh
        volumes:
            - ./server/:/code
            - media:/media
        ports:
            - '8005:8005'
        depends_on:
            - db

    client:
        image: docker.pkg.github.com/toggle-corp/worldvision-dvs/client:latest
        build:
          context: ./client/
          cache_from:
            - devtc/worldvision-dvs:client-latest
        env_file:
            - .env
        command: bash -c '/code/scripts/run_develop.sh'
        volumes:
            - ./client/:/code
        ports:
            - '3005:3005'

volumes:
  media:
  postgres-data:
