version: '3.2'

services:
    db:
        image: postgres:9.6
        volumes:
            - ./data/postgres-data:/var/lib/postgresql/data

    server:
        image: devtc/worldvision-dvs:server-release
        env_file:
            - .env-prod
        command: bash -c '/code/scripts/wait-for-it.sh db:5432 && /code/scripts/run_develop.sh'
        volumes:
            - ./data/media:/media
        ports:
            - '8005:8005'
        depends_on:
            - db

    client:
        image: devtc/worldvision-dvs:client-release
        env_file:
            - .env-prod
        command: bash -c '/code/scripts/run_develop.sh'
        ports:
            - '80:3005'
