version: '3.2'

services:
  db:
    image: postgres:9.6
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data

  server:
    image: docker.pkg.github.com/toggle-corp/worldvision-dvs/server:release
    env_file:
      - .env-prod
    volumes:
      - server-static:/static
      - ./data/media:/media
    depends_on:
      - db

  client:
    image: docker.pkg.github.com/toggle-corp/worldvision-dvs/client:release
    volumes:
      - client-static:/build/
    env_file:
      - .env-prod
    command: bash -c '/code/scripts/sync_build.sh'

  caddy:
    image: caddy:2.2.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # App volumes mapping
      - client-static:/var/www/
      - server-static:/var/www/django-static/
      - ./data/media:/var/www/django-media/
      # Caddy volumes
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - server


volumes:
  server-static:
  client-static:
  caddy_data:
  caddy_config:
