version: '3.2'

services:
    db:
        image: postgres:9.6
        volumes:
          - ./data/postgres-data:/var/lib/postgresql/data

    server:
        image: devtc/worldvision-dvs:server-release
        env_file:
          - .env-prod
        volumes:
          - server-static:/static
          - ./data/media:/media
        depends_on:
          - db

    client:
        image: devtc/worldvision-dvs:client-release
        volumes:
          - client-static:/build/
        env_file:
          - .env-prod
        command: bash -c '/code/scripts/sync_build.sh'

    nginx: # NGINX Server
        image: nginx:1.13
        volumes:
          - ./nginx/:/etc/nginx/conf.d/:z
          - server-static:/static/server/
          - client-static:/static/client/
          - ./data/media:/media/server/
        ports:
          - '80:80'
          - '8005:8005'
        depends_on:
          - server

volumes:
  server-static:
  client-static:
