# Generated by Django 2.1 on 2018-09-11 08:54

from django.db import migrations
from django.core.management import call_command


def re_extract_reports(apps, schema_editor):
    call_command('force_extract_reports')


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20180828_1815'),
    ]

    operations = [
        migrations.RunPython(re_extract_reports),
    ]
