# Generated by Django 2.1.2 on 2018-11-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0010_reload_municipalities'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('projects', models.ManyToManyField(to='project.Project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
