# Generated by Django 2.1 on 2018-09-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_load_initial_districts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name']},
        ),
    ]
