# Generated by Django 2.1 on 2018-09-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20180911_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.District'),
        ),
    ]
