# Generated by Django 2.1 on 2018-10-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20181030_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='municipality',
            new_name='municipalities',
        ),
    ]
