# Generated by Django 2.1.12 on 2020-02-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0002_auto_20181030_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='child_family_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='child_family_start_date',
            field=models.DateField(null=True),
        ),
    ]
