# Generated by Django 2.1.12 on 2020-08-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0003_auto_20200204_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='child_family_end_date',
            field=models.DateField(null=True, verbose_name='Child family support/participation end date'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='child_family_start_date',
            field=models.DateField(null=True, verbose_name='Child family support/participation start date'),
        ),
    ]
